Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 8
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	compute_duplicability
	1	compute_universality
	1	create_orthology_dictionaries
	1	merge_features
	5

[Tue Oct 20 14:24:20 2020]
rule create_orthology_dictionaries:
    input: data/orthology_anophelinae.tsv
    output: results/orthogroups.pickle, results/genes.pickle
    jobid: 4

[Tue Oct 20 14:24:22 2020]
Finished job 4.
1 of 5 steps (20%) done

[Tue Oct 20 14:24:22 2020]
rule compute_duplicability:
    input: results/orthogroups.pickle
    output: results/evol_feat_orthogroups/DUP_orthogroups.tsv, results/evol_feat_genes/DUP_genes.tsv
    jobid: 3


[Tue Oct 20 14:24:22 2020]
rule compute_universality:
    input: results/orthogroups.pickle
    output: results/evol_feat_orthogroups/UNI_orthogroups.tsv, results/evol_feat_genes/UNI_genes.tsv
    jobid: 2

[Tue Oct 20 14:24:22 2020]
Error in rule compute_duplicability:
    jobid: 3
    output: results/evol_feat_orthogroups/DUP_orthogroups.tsv, results/evol_feat_genes/DUP_genes.tsv

RuleException:
CalledProcessError in line 33 of /home/lruzzant/evol-feat-snakemake/workflow/Snakefile:
Command 'set -euo pipefail;  /home/lruzzant/miniconda3/envs/evol-feat/bin/python3.7 /home/lruzzant/evol-feat-snakemake/workflow/.snakemake/scripts/tmpv78ncipo.compute_duplicability.py' returned non-zero exit status 1.
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2229, in run_wrapper
  File "/home/lruzzant/evol-feat-snakemake/workflow/Snakefile", line 33, in __rule_compute_duplicability
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 551, in _callback
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 537, in cached_or_run
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2241, in run_wrapper
[Tue Oct 20 14:24:23 2020]
Finished job 2.
2 of 5 steps (40%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/lruzzant/evol-feat-snakemake/workflow/.snakemake/log/2020-10-20T142420.673801.snakemake.log
