Building DAG of jobs...
Updating job 1 (merge_features).
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	compute_age
	1	compute_universality
	1	create_mrca_branchlengths_table
	1	create_orthology_dictionaries
	1	merge_features
	6

[Mon Feb 15 18:37:12 2021]
rule create_orthology_dictionaries:
    input: input/apoidea_orthology.txt
    output: output/orthogroups.pickle, output/genes.pickle
    jobid: 5

[Mon Feb 15 18:37:22 2021]
Finished job 5.
1 of 6 steps (17%) done

[Mon Feb 15 18:37:22 2021]
rule compute_universality:
    input: output/orthogroups.pickle
    output: output/computed_orthogroup_features/UNI.tsv
    jobid: 3

[Mon Feb 15 18:37:22 2021]
Error in rule compute_universality:
    jobid: 3
    output: output/computed_orthogroup_features/UNI.tsv

RuleException:
URLError in line 37 of /mnt/c/Users/livio/evol-feat-snakemake/workflow/rules/compute_features.smk:
<urlopen error [Errno 2] No such file or directory: '/mnt/c/Users/livio/evol-feat-snakemake/workflow/scripts/compute_UNI.py'>
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2229, in run_wrapper
  File "/mnt/c/Users/livio/evol-feat-snakemake/workflow/rules/compute_features.smk", line 37, in __rule_compute_universality
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/urllib/request.py", line 222, in urlopen
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/urllib/request.py", line 525, in open
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/urllib/request.py", line 543, in _open
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/urllib/request.py", line 503, in _call_chain
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/urllib/request.py", line 1451, in file_open
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/urllib/request.py", line 1490, in open_local_file
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 551, in _callback
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 537, in cached_or_run
  File "/home/lruzzant/miniconda3/envs/evol-feat/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2241, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /mnt/c/Users/livio/evol-feat-snakemake/workflow/.snakemake/log/2021-02-15T183712.288731.snakemake.log
